LIBERTY = 'liberty'
MITAKA = 'mitaka'
NEWTON = 'newton'

OPENSTACK_VERSIONS = [LIBERTY, MITAKA, NEWTON]

READY_FOR_UPGRADE = 'READY FOR UPGRADE'
UPGRADE_IN_PROGRESS = 'UPGRADE IN PROGRESS'
UPGRADE_PAUSED = 'UPGRADE PAUSED'
UPGRADE_ERROR = 'UPGRADE ERROR'
UPGRADE_CANCELLED = 'UPGRADE CANCELLED'

STATUSES = [READY_FOR_UPGRADE,
            UPGRADE_IN_PROGRESS,
            UPGRADE_PAUSED,
            UPGRADE_ERROR,
            UPGRADE_CANCELLED]
