LIBERTY = 'liberty'
MITAKA = 'mitaka'
NEWTON = 'newton'
UNKNOWN = 'unknown'

OPENSTACK_VERSIONS = [UNKNOWN, LIBERTY, MITAKA, NEWTON]

READY_FOR_UPGRADE = 'READY FOR UPGRADE'
UPGRADE_IN_PROGRESS = 'UPGRADE IN PROGRESS'
UPGRADE_PAUSED = 'UPGRADE PAUSED'
UPGRADE_ERROR = 'UPGRADE ERROR'
UPGRADE_CANCELLED = 'UPGRADE CANCELLED'
NOT_READY_FOR_UPGRADE = 'NOT READY FOR UPGRADE'
UPGRADE_ROLLBACK = 'UPGRADE ROLLBACK IN PROGRESS'

STATUSES = [READY_FOR_UPGRADE,
            UPGRADE_IN_PROGRESS,
            UPGRADE_PAUSED,
            UPGRADE_ERROR,
            UPGRADE_CANCELLED,
            UPGRADE_ROLLBACK,
            NOT_READY_FOR_UPGRADE]

ANSIBLE = 'ansible'
PUPPET = 'puppet'
FUEL = 'fuel'

DEPLOY_DRIVERS = [ANSIBLE, PUPPET, FUEL]

OPENSTACK = 'openstack'

DISCOVERY_METHODS = [OPENSTACK]
